### ISSUE TITLE
revisit github code on master

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jumpscale_core8#178]
see
https://github.com/Jumpscale/jumpscale_core8/blob/master/lib/JumpScale/clients/github/Github.py

- there is a serious conflict between master & branch ays_consume
- code got moved into github client which
    - is not specific to github, is for all git
    - is now 90+% duplicate code with install tools
    - was trying to fix something which was not broken at first place

we need to check
- do we need this change, if yes why
- the executor in installtools is indeed a hack, but is it OK to leave ? what are downsides?

**Comment by rkhamis** [comment]
We could move the github work to git.
But we shouldn't just revert the changes
Having the executor in InstallTools:

1. Logically doesn't make sense. This is supposed to be only for bootstrapping.
2. The executor that gets set as `self` [here](https://github.com/Jumpscale/jumpscale_core8/blob/b7f9854c1edc90d16cda8d5eb1a4f537b131a8ab/install/InstallTools.py#L1684) is wrong in every possible way
3. This breaks JS installation, because having set `executor` to `self`, instead of an executor object (which isn't even available at this time), the executor doesn't have `cuisine`, which is referenced [here](https://github.com/Jumpscale/jumpscale_core8/blob/a0dd8ff97547b0ab486e73b9b9fa361999de0682/install/InstallTools.py#L1684)

**Comment by despiegk** [comment]
- there are more items in install tools using cuisine, potentially argument can be made that this is still better than duplication
- executor to None should be better but then again its lots of extra work, someone should look into this
- it should not break js installation, it didn't before so something changed then?

lets discuss but for now we need something working for
- install
- for cuisine

and needs to be working NOW
without breaking all kinds of other things like we did before

**Comment by rkhamis** [comment]
We already have a lot of duplication, especially in FS.
So far the executors are only in the git methods. If we're going to add executors to InstallTools methods, we might as well do it right.

For now, I'll do a quick fix to keep the installation working, but we need to take a conscious decision regarding which approach we'll take.
