### ISSUE TITLE
G8OS sal support

### ISSUE THREAD

**Issue by FastGeert** [Jumpscale/jumpscale_core8#778]
To write the AYS'ses for G8OS grid we need a sal wrapping the g8core python client library to administer the g8os nodes.

See https://pypi.python.org/pypi/g8core

**Comment by grimpy** [comment]
https://github.com/Jumpscale/jumpscale_core8/tree/8.2.0/lib/JumpScale/clients/g8core
this seems to exist? Not sure how g8core library is installed though

**Comment by zaibon** [comment]
>https://github.com/Jumpscale/jumpscale_core8/tree/8.2.0/lib/JumpScale/clients/g8core
this seems to exist? Not sure how g8core library is installed though

This is not a sal, this is just the client itself.
G8core package is installed with pip, but since 0.12.0 has not been release yet, installation of this version of the client has to be done manually.
- clone https://github.com/g8os/core0/tree/master/pyclient
-  link the pyclient  folder in your PYTHONPATH

**Comment by zaibon** [comment]
I have a WIP for the SAL itself, I just pushed it, see : https://github.com/Jumpscale/jumpscale_core8/commit/ec46c254e45c66a32c3e87db0a9980813f726380

**Comment by rkhamis** [comment]
@zaibon what's the status here? Should I keep it open?

**Comment by grimpy** [comment]
It's kindda ongong process adjustments are still being made.
